### ISSUE TITLE
开启 es6转 es5的话就不能用了

### ISSUE THREAD

**Issue by hamletfei** [zarknight/owx#1]
微信小程序开发工具开启开启 es6转 es5的话就不能用了，如果不开启又怕低版本的手机不支持 es6的语法

**Comment by zarknight** [comment]
我这边开发的时候也是一直开启“ES6转ES5”，都是可以的。不知道你开启了有什么问题？报什么错误信息么？

**Comment by hamletfei** [comment]
代开之后报这个错
VM2856:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'mark' of undefined 
 TypeError: Cannot read property 'mark' of undefined
    at http://127.0.0.1:60569/appservice/datamanage/wj.js:4:66
    at http://127.0.0.1:60569/appservice/datamanage/wj.js:22:2
    at require (http://127.0.0.1:60569/appservice/__dev__/WAService.js:22:25737)
    at http://127.0.0.1:60569/appservice/__dev__/WAService.js:22:25383
    at http://127.0.0.1:60569/appservice/page/index/index.js:3:10
    at require (http://127.0.0.1:60569/appservice/__dev__/WAService.js:22:25737)
    at http://127.0.0.1:60569/appservice/appservice?t=1532917378145:1678:9

**Comment by zarknight** [comment]
你这边是clone下来的代码就有这样的错误么？能告诉我你的操作系统版本之类的信息么？

我这边找了Mac和Windows 10的测试了一下，都没发现你这个问题。

**Comment by hamletfei** [comment]
我发现在同一个文件中写就不行，比如下面这个写法就不行  如果 test3写在另一个js中去调用 test2就行，不知道是什么原因  楼主可否解惑一下
function test2() {
    return new Promise((resolve, reject) => {
        setTimeout(()=>{
            resolve('test2');
        }, 1000);
    })
}

async function test3() {
    let result = await test2();
    return result;
}

**Comment by zarknight** [comment]
请检查要使用async / await语法的代码文件中是否引入了regeneratorRuntime，可以参考index.js（https://github.com/zarknight/owx/blob/master/pages/index/index.js）里的那句：

const { regeneratorRuntime } = global

**Comment by SuperAL** [comment]
@hamletfei 
我也遇到该报错：
```
thirdScriptError
sdk uncaught third Error
Cannot read property 'mark' of undefined
TypeError: Cannot read property 'mark' of undefined
```
我本来是这样定义方法的：
```
async function getNetworkType() {}
```
改成下面那样就好了：
```
const getNetworkType = async () => {}
```
